version: '0.1'

services:
    jupyterhub:
        build:
        ports:
            - 8888:8888
        networks:
            - dcsg-jup-net

    kernel-gateway:
        image: 
        command: 
        pid: 
        volumes:
            - 
            - 
        networks:
            - dcsg-jup-net

#### leftovers from example compose file
#    grafana:
#        image: grafana/grafana
#        volumes:
#            - grafana_data:/var/lib/grafana
#        ports:
#            - 3000:3000
#        networks:
#            - default
#    dcgm_exporter:
#        image: nvidia/dcgm-exporter:1.4.3
#        runtime: nvidia
#        volumes:
#            - prometheus_textfiles:/run/prometheus
#        networks:
#            - default
#
#volumes:
#    prometheus_textfiles:
#        driver_opts:
#            type: tmpfs
#            device: tmpfs
#    prometheus_data:
#        driver: local
#    grafana_data:
#        driver: local
#
#networks:
#    default:
#        driver: bridge
